management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
server:
  servlet:
    context-path: /bh
  port: 8080
spring:
  jmx:
    enabled: true
  flyway:
    baseline-on-migrate: true
    schemas: BLUEHARVEST
    defaultSchema: BLUEHARVEST
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: BLUEHARVEST
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:bh;NON_KEYWORDS=user
    username: sa
    password: password
logging:
  level:
    root: info
    com:
      blueharvest: debug